name: Raise Your Resilience
favicon: null
layout_spectrum: 0.1225895513780415
typography_spectrum: 0.23600116628222167
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3238877758849412
  lightness: 0.38089156872592866
  saturation: 0.09131082170642912
  rhythmicContrast: 0.588149347808212
purpose: []
